# Generated by Django 4.2.16 on 2026-03-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('booking_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость брони (₽)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('used', 'Использована'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='stations.connector', verbose_name='Разъём')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
            },
        ),
    ]
