# Generated by Django 4.2.16 on 2026-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('notification_type', models.CharField(choices=[('charging_start', 'Начало зарядки'), ('charging_end', 'Конец зарядки'), ('booking_created', 'Бронь создана'), ('booking_expired', 'Бронь истекла'), ('station_available', 'Станция доступна'), ('energy_update', 'Обновление энергии')], max_length=30, verbose_name='Тип уведомления')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Токен')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, verbose_name='Платформа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Push-токен',
                'verbose_name_plural': 'Push-токены',
                'ordering': ['-updated_at'],
            },
        ),
    ]
