# Generated by Django 4.2.16 on 2026-03-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Энергия (кВт·ч)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость (₽)')),
                ('current_power_kw', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Текущая мощность (кВт)')),
                ('payment_method', models.CharField(choices=[('wallet', 'Кошелёк'), ('qr', 'QR-код')], default='wallet', max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции')),
                ('ocpp_transaction_id', models.IntegerField(blank=True, null=True, verbose_name='OCPP ID транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='bookings.booking', verbose_name='Бронь')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='stations.connector', verbose_name='Разъём')),
            ],
            options={
                'verbose_name': 'Зарядная сессия',
                'verbose_name_plural': 'Зарядные сессии',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200, verbose_name='Название станции')),
                ('station_address', models.CharField(max_length=500, verbose_name='Адрес станции')),
                ('connector_type', models.CharField(max_length=50, verbose_name='Тип разъёма')),
                ('energy_kwh', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Энергия (кВт·ч)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (₽)')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('start_time', models.DateTimeField(verbose_name='Начало зарядки')),
                ('end_time', models.DateTimeField(verbose_name='Конец зарядки')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Номер чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='charging.chargingsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-created_at'],
            },
        ),
    ]
