# Generated by Django 4.2.16 on 2026-03-12 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
