# Generated by Django 4.2.16 on 2026-03-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stations/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('working_hours', models.CharField(blank=True, default='24/7', max_length=100, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Зарядная станция',
                'verbose_name_plural': 'Зарядные станции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('type2', 'Type 2'), ('ccs', 'CCS'), ('chademo', 'CHAdeMO'), ('type1', 'Type 1')], default='type2', max_length=20, verbose_name='Тип разъёма')),
                ('power_kw', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Мощность (кВт)')),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за кВт·ч (₽)')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('busy', 'Занят'), ('broken', 'Неисправен'), ('reserved', 'Забронирован')], default='free', max_length=20, verbose_name='Статус')),
                ('connector_number', models.IntegerField(verbose_name='Номер разъёма')),
                ('image', models.ImageField(blank=True, null=True, upload_to='connectors/', verbose_name='Изображение')),
                ('ocpp_connector_id', models.IntegerField(default=1, verbose_name='OCPP ID разъёма')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='stations.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Разъём',
                'verbose_name_plural': 'Разъёмы',
                'ordering': ['connector_number'],
            },
        ),
    ]
